// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxatpxdtnsnpgkrgvdvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4YXRweGR0bnNucGdrcmd2ZHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTcwODYsImV4cCI6MjA1ODc3MzA4Nn0.sgeFlVz_1CnC8R6gx4m2M2duxo06EwtYK4BA0-zf2nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);